name = "MOCNeutronTransport"
uuid = "b01d8a8e-7766-460c-9f6b-9e1abe3a94ae"
authors = ["Kyle Vaughn <kcvaughn@umich.edu>"]
version = "0.1.0"

[deps]
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[compat]
StructArrays = "0.5"
julia = "1.4.1"
