spack:
  specs:
    - cmake
    - hdf5
    - gmsh
    - pugixml
    - benchmark
  view: true
  packages:
    all:
      compiler: [clang@15, gcc@12]
    hdf5:
      require: +cxx+fortran~mpi
    gmsh:
      require: +openmp+cairo+fltk+opencascade+eigen+hdf5 ^scotch~mpi
    opengl:
      buildable: false
  concretizer:
    unify: true
