name: CI 

on: [push]

jobs:
  main:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      matrix:
        compiler: [ gcc, clang ]
        build_type: [ Release, Debug ]
        cuda: [ OFF ]
        openmp: [ OFF, ON ]
        dev_mode: [ OFF, ON ]

    name: "${{ matrix.compiler }}, ${{ matrix.build_type }}, OMP=$${{ matrix.openmp }}, 
      Dev=$${{ matrix.dev_mode }}"

    steps:
      - uses: actions/checkout@v3

      - name: Set up gcc 
        shell: bash
        if: matrix.compiler == 'gcc'
        run: |
          sudo apt -y update
          sudo apt install -y gcc-12 g++-12 clang-14
          export CC=gcc-12
          export CXX=g++-12

      - name: Set up clang 
        shell: bash
        if: matrix.compiler == 'clang' 
        run: |
          sudo apt -y update
          sudo apt install -y clang-14
          export CC=clang-14
          export CXX=clang++-14

      - name: OpenMP
        shell: bash
        if: matrix.openmp == 'ON'
        run: sudo apt install -y libomp-14-dev

      - name: Dev mode dependencies
        shell: bash
        if: matrix.dev_mode == 'ON'
        run: |
          sudo apt install -y cppcheck

      - name: Configure and build
        run: |
          cmake -S . -B build \
                -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                -DUM2_ENABLE_CUDA=${{ matrix.cuda }} \
                -DUM2_ENABLE_OPENMP=${{ matrix.openmp }} \
                -DUM2_DEV_MODE=${{ matrix.dev_mode }}
          make -C build

      - name: Run tests
        run: 
          make -C build test 
